image: node:10.15.3
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@10.0.1
    - npm install
    - npm run build:pages
  artifacts:
    paths:
      - public
  only:
    - master
